# Generated by Django 3.2.4 on 2021-07-18 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('date_Of_Oreder', models.DateField()),
                ('amount', models.FloatField(default=100)),
                ('product_details', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order_Master',
            },
        ),
    ]
